from database import SessionLocal, Base, engine
import models

def seed_db():
    # Create tables
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    
    # Clear tables to prevent duplication and ensure fresh seed
    db.query(models.Application).delete()
    db.query(models.SavedScholarship).delete()
    db.query(models.Scholarship).delete()
    db.query(models.User).delete()
    db.commit()

    scholarships = [
        {
            "id": 1,
            "name": "National Merit Scholarship (MHRD)",
            "provider": "Ministry of Human Resource Development, Govt of India",
            "description": "Financial assistance for meritorious students from low-income families to meet a part of their day-to-day expenses while pursuing higher studies.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 8.0,
            "min_percentage": 80.0,
            "category": "General",
            "max_income": 800000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Merit-cum-Means",
            "amount": "₹ 20,000 / Year",
            "last_date": "2026-10-31",
            "official_website": "https://scholarships.gov.in",
            "documents": "Class 12 Marksheet,Income Certificate,Caste Certificate,Aadhaar Card,Bank Passbook",
            "benefits": "₹10,000 per annum for the first three years of undergraduate studies, and ₹20,000 per annum for postgraduate studies."
        },
        {
            "id": 2,
            "name": "AICTE Pragati Scholarship for Girls",
            "provider": "All India Council for Technical Education (AICTE)",
            "description": "Empowering girls to pursue technical education by providing financial assistance. Maximum two girls per family can apply.",
            "qualification": "10th",
            "current_course": "Diploma",
            "min_cgpa": 6.0,
            "min_percentage": 60.0,
            "category": "All",
            "max_income": 800000.0,
            "state": "All",
            "district": "All",
            "gender": "Female",
            "field_of_study": "STEM",
            "type": "Merit",
            "amount": "₹ 50,000 / Year",
            "last_date": "2026-11-15",
            "official_website": "https://www.aicte-india.org",
            "documents": "Admit Card/Marksheet,Income Certificate,Tuition Fee Receipt,Category Certificate,Aadhaar Card",
            "benefits": "₹50,000 per annum directly transferred as lump sum amount to meet tuition fee, purchase of books, equipment, and soft wares."
        },
        {
            "id": 3,
            "name": "Adobe Research Women-in-Technology Scholarship",
            "provider": "Adobe Research",
            "description": "Recognizing outstanding female students in computer science and technology globally, encouraging them to excel in STEM fields.",
            "qualification": "Undergraduate",
            "current_course": "Undergraduate",
            "min_cgpa": 8.5,
            "min_percentage": 85.0,
            "category": "All",
            "max_income": 999999999.0,
            "state": "All",
            "district": "All",
            "gender": "Female",
            "field_of_study": "STEM",
            "type": "Merit",
            "amount": "$ 20,000 (One-time)",
            "last_date": "2026-09-30",
            "official_website": "https://research.adobe.com/scholarship/",
            "documents": "Resume/CV,Academic Transcripts,3 Letters of Recommendation,Statement of Purpose",
            "benefits": "A one-time scholarship of $20,000. Plus, a mentorship program and an internship opportunity at Adobe Research."
        },
        {
            "id": 4,
            "name": "Reliance Foundation Undergraduate Scholarship",
            "provider": "Reliance Foundation",
            "description": "Supporting meritorious students from diverse backgrounds across India to pursue undergraduate education in any stream.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 7.0,
            "min_percentage": 70.0,
            "category": "All",
            "max_income": 1500000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Merit-cum-Means",
            "amount": "₹ 2,00,000 (Up to)",
            "last_date": "2026-10-15",
            "official_website": "https://www.reliancefoundation.org",
            "documents": "Class 10 & 12 Marksheets,Income Certificate,Bonafide Student Certificate,Aadhaar Card",
            "benefits": "Support of up to ₹2,00,000 over the duration of the degree course plus access to a strong alumni network and mentorship."
        },
        {
            "id": 5,
            "name": "INSPIRE Scholarship for Higher Education (SHE)",
            "provider": "Department of Science & Technology, Govt of India",
            "description": "Attracting talented youth to study natural and basic sciences at the Bachelor and Master levels.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 8.0,
            "min_percentage": 80.0,
            "category": "All",
            "max_income": 999999999.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "STEM",
            "type": "Merit",
            "amount": "₹ 80,000 / Year",
            "last_date": "2026-12-31",
            "official_website": "https://online-inspire.gov.in",
            "documents": "Class 12 Marksheet (Top 1% rank),Class 10 Certificate,Principal Recommendation Letter",
            "benefits": "Annual scholarship of ₹80,000, consisting of ₹60,000 cash stipend and ₹20,000 mentorship support for research projects."
        },
        {
            "id": 6,
            "name": "HDFC Bank Parivartan's ECS Scholarship",
            "provider": "HDFC Bank",
            "description": "Assisting students from marginalized sections of society who are facing crisis situations that might interrupt their education.",
            "qualification": "10th",
            "current_course": "Undergraduate",
            "min_cgpa": 6.0,
            "min_percentage": 60.0,
            "category": "All",
            "max_income": 600000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Means",
            "amount": "₹ 75,000 / Year",
            "last_date": "2026-09-15",
            "official_website": "https://www.hdfcbank.com",
            "documents": "Previous Year Marksheet,Income Proof,Proof of Crisis,Admission Proof",
            "benefits": "Financial assistance up to ₹75,000 for undergraduate and post-graduate studies to cover fees and academic costs."
        },
        {
            "id": 7,
            "name": "Kotak Kanya Scholarship",
            "provider": "Kotak Education Foundation",
            "description": "Financial support to meritorious girl students from low-income families to pursue higher education from top-tier institutes.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 7.5,
            "min_percentage": 75.0,
            "category": "All",
            "max_income": 600000.0,
            "state": "Maharashtra",
            "district": "All",
            "gender": "Female",
            "field_of_study": "All",
            "type": "Merit-cum-Means",
            "amount": "₹ 1,50,000 / Year",
            "last_date": "2026-09-30",
            "official_website": "https://kotakeducation.org",
            "documents": "Class 12 Marksheet,Income Certificate,College Admission Proof,Parent Identity Proof",
            "benefits": "Scholarship of ₹1.5 Lakh per year covering tuition fees, hostel, books, and living expenses."
        },
        {
            "id": 8,
            "name": "ONGC Scholarship Scheme for SC/ST/OBC Students",
            "provider": "ONGC Foundation",
            "description": "Exclusive scholarship for students belonging to Scheduled Caste, Scheduled Tribe, and OBC categories pursuing professional courses.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 6.0,
            "min_percentage": 60.0,
            "category": "SC/ST/OBC",
            "max_income": 450000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "STEM",
            "type": "Merit-cum-Means",
            "amount": "₹ 48,000 / Year",
            "last_date": "2026-10-15",
            "official_website": "https://ongcfoundation.org",
            "documents": "Caste Certificate,Income Certificate,Admission Letter,Qualifying Marksheet",
            "benefits": "Annual aid of ₹48,000 to cover course fee, books, and boarding charges."
        },
        {
            "id": 9,
            "name": "L'Oréal India For Young Women in Science Scholarship",
            "provider": "L'Oréal India",
            "description": "Encouraging young women to pursue careers in science by providing financial aid for their college education.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 8.5,
            "min_percentage": 85.0,
            "category": "All",
            "max_income": 600000.0,
            "state": "All",
            "district": "All",
            "gender": "Female",
            "field_of_study": "STEM",
            "type": "Merit",
            "amount": "₹ 2,50,000 (Total)",
            "last_date": "2026-10-20",
            "official_website": "https://www.loreal.com",
            "documents": "Class 10 & 12 Marksheets,Parent Income Certificate,Aadhaar Card,Admission Letter",
            "benefits": "₹2.5 Lakhs paid over the duration of the science-related undergraduate degree."
        },
        {
            "id": 10,
            "name": "Post Matric Scholarship Scheme for Minorities",
            "provider": "Ministry of Minority Affairs, Govt of India",
            "description": "Financial assistance to students belonging to minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) to pursue higher studies.",
            "qualification": "10th",
            "current_course": "Undergraduate",
            "min_cgpa": 5.0,
            "min_percentage": 50.0,
            "category": "Minority",
            "max_income": 200000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Means",
            "amount": "₹ 15,000 / Year",
            "last_date": "2026-11-30",
            "official_website": "https://scholarships.gov.in",
            "documents": "Minority Status Declaration,Income Certificate,Last Exam Marksheet,Aadhaar Card",
            "benefits": "Admission & tuition fee waiver along with a monthly maintenance allowance for day scholars and hostellers."
        },
        {
            "id": 11,
            "name": "LIC HFL Vidyadhan Scholarship",
            "provider": "LIC Housing Finance Limited",
            "description": "Empowering lower-income group students to complete their higher secondary, graduation, or post-graduation courses.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 6.0,
            "min_percentage": 60.0,
            "category": "All",
            "max_income": 360000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Means",
            "amount": "₹ 25,000 / Year",
            "last_date": "2026-09-30",
            "official_website": "https://www.lichousing.com",
            "documents": "Class 12 Marksheet,Income Certificate,Fee Receipt,ID Proof",
            "benefits": "Scholarship of ₹25,000 per year for 3 years to cover undergraduate academic expenses."
        },
        {
            "id": 12,
            "name": "Central Sector Scheme of Scholarship for College Students",
            "provider": "Department of Higher Education, Govt of India",
            "description": "Supporting students who are above 80th percentile of successful candidates in the relevant stream from the respective Board of Examination.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 8.0,
            "min_percentage": 80.0,
            "category": "All",
            "max_income": 450000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Merit",
            "amount": "₹ 20,00,000 (Max)",
            "last_date": "2026-10-31",
            "official_website": "https://scholarships.gov.in",
            "documents": "Class 12 Marksheet,Income Declaration,Aadhaar Card,College Head Joining Report",
            "benefits": "₹12,000 per year for graduation (first three years) and ₹20,000 per year for post-graduation."
        },
        {
            "id": 13,
            "name": "Google Generation Scholarship (APAC) - STEM",
            "provider": "Google LLC",
            "description": "Helping aspiring computer scientists excel in technology and become leaders in the field. Focuses on underrepresented groups in tech.",
            "qualification": "Undergraduate",
            "current_course": "Undergraduate",
            "min_cgpa": 8.0,
            "min_percentage": 80.0,
            "category": "All",
            "max_income": 999999999.0,
            "state": "All",
            "district": "All",
            "gender": "Female",
            "field_of_study": "STEM",
            "type": "Merit",
            "amount": "$ 2,500 (One-time)",
            "last_date": "2026-08-31",
            "official_website": "https://buildyourfuture.withgoogle.com/scholarships",
            "documents": "Resume/CV,Transcripts,Two essay responses,Enrollment Letter",
            "benefits": "A one-time award of $2,500 to support tuition, books, and supplies, plus invitations to Google networking events."
        },
        {
            "id": 14,
            "name": "Commonwealth Master's Scholarship (UK)",
            "provider": "Commonwealth Scholarship Commission, UK",
            "description": "Full scholarship for students from developing Commonwealth countries to study a Master's degree in the United Kingdom.",
            "qualification": "Undergraduate",
            "current_course": "Postgraduate",
            "min_cgpa": 7.5,
            "min_percentage": 75.0,
            "category": "All",
            "max_income": 999999999.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Merit",
            "amount": "Full Funding (UK)",
            "last_date": "2026-10-18",
            "official_website": "https://cscuk.fcdo.gov.uk",
            "documents": "Degree Certificate,2 Letters of Recommendation,Passport Copy,UK Uni Offer Letter",
            "benefits": "Covers full airfare, tuition fees, monthly living allowance (£1,300+), warm clothing allowance, and study travel grants."
        },
        {
            "id": 15,
            "name": "Inlaks Shivdasani Foundation Scholarship",
            "provider": "Inlaks Shivdasani Foundation",
            "description": "Funding for young Indian citizens with outstanding talent to pursue postgraduate degrees, research, or training at top global institutions.",
            "qualification": "Undergraduate",
            "current_course": "Postgraduate",
            "min_cgpa": 8.0,
            "min_percentage": 80.0,
            "category": "All",
            "max_income": 999999999.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "Arts/Humanities",
            "type": "Merit",
            "amount": "$ 100,000 (Max)",
            "last_date": "2026-09-15",
            "official_website": "https://www.inlaksfoundation.org",
            "documents": "Admission Evidence,Resume,Arts Portfolio,2 Reference Letters",
            "benefits": "Covers tuition fees, living expenses, one-way travel up to a maximum limit of $100,000."
        },
        {
            "id": 16,
            "name": "Fulbright-Nehru Master's Fellowships",
            "provider": "USIEF (US-India Educational Foundation)",
            "description": "Fellowships designed for highly motivated Indian students to pursue Master's programs at selected US universities.",
            "qualification": "Undergraduate",
            "current_course": "Postgraduate",
            "min_cgpa": 7.0,
            "min_percentage": 70.0,
            "category": "All",
            "max_income": 999999999.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Merit",
            "amount": "Fully Funded (US)",
            "last_date": "2026-08-15",
            "official_website": "https://www.usief.org.in",
            "documents": "Graduate transcripts,3 Reference Letters,TOEFL/IELTS Scorecard,Statement of Purpose",
            "benefits": "J-1 visa support, full funding for tuition and fees, living stipend, round-trip economy class travel, and accident health insurance."
        },
        {
            "id": 17,
            "name": "Legrand Scholarship Program",
            "provider": "Legrand India",
            "description": "Encouraging higher education for girl students, children of dealers/retailers, and specially-abled children to pursue Engineering/STEM fields.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 7.0,
            "min_percentage": 70.0,
            "category": "All",
            "max_income": 500000.0,
            "state": "All",
            "district": "All",
            "gender": "Female",
            "field_of_study": "STEM",
            "type": "Merit-cum-Means",
            "amount": "₹ 60,000 / Year",
            "last_date": "2026-10-31",
            "official_website": "https://www.legrand.co.in",
            "documents": "Class 12 Marksheet,Income Certificate,Admission Letter,Passport photo",
            "benefits": "Covers 60% of tuition fees or ₹60,000 per year (whichever is lower) for the complete engineering course."
        },
        {
            "id": 18,
            "name": "Siemens Scholarship Program",
            "provider": "Siemens India",
            "description": "Nurturing engineering talent from economically disadvantaged backgrounds, preparing them for industrial challenges.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 6.0,
            "min_percentage": 60.0,
            "category": "All",
            "max_income": 200000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "STEM",
            "type": "Means",
            "amount": "Full Tuition Fee",
            "last_date": "2026-09-30",
            "official_website": "https://www.siemens.co.in",
            "documents": "1st yr engineering admission slip,SSC & HSC Marksheets,Income Proof",
            "benefits": "Covers 100% tuition fees, hostel/transport allowances, and provides advanced soft skills and corporate training."
        },
        {
            "id": 19,
            "name": "Narotam Sekhsaria Scholarship Program",
            "provider": "Narotam Sekhsaria Foundation",
            "description": "Interest-free loan scholarships for PG/Doctorate programs at prestigious international and Indian universities.",
            "qualification": "Undergraduate",
            "current_course": "Postgraduate",
            "min_cgpa": 8.0,
            "min_percentage": 80.0,
            "category": "All",
            "max_income": 999999999.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Merit",
            "amount": "₹ 20,00,000 (Max)",
            "last_date": "2026-09-01",
            "official_website": "https://pg.nsfoundation.co.in",
            "documents": "Transcripts,GRE/GMAT scores,Admission Letter,Letter of Recommendations",
            "benefits": "Interest-free loan scholarship of up to ₹20 lakhs, paired with exceptional mentoring by foundation trustees."
        },
        {
            "id": 20,
            "name": "Sahu Jain Trust Undergraduate Scholarship",
            "provider": "Sahu Jain Trust",
            "description": "Financial support for students pursuing general undergraduate degrees or vocational technical education in India.",
            "qualification": "Intermediate",
            "current_course": "Undergraduate",
            "min_cgpa": 6.5,
            "min_percentage": 65.0,
            "category": "All",
            "max_income": 300000.0,
            "state": "All",
            "district": "All",
            "gender": "All",
            "field_of_study": "All",
            "type": "Means",
            "amount": "₹ 15,000 / Year",
            "last_date": "2026-10-15",
            "official_website": "https://sahujaintrust.timesofindia.com",
            "documents": "Previous marksheets,Employer/Authority income proof,Recommendation letter",
            "benefits": "Recurring annual support ranging between ₹2,500 to ₹15,000 based on course and merit evaluation."
        }
    ]

    for s in scholarships:
        db.add(models.Scholarship(**s))
    
    # Also add a default mock student user for login/auth simulation
    default_user = models.User(
        id=1,
        username="jane_doe",
        qualification="Intermediate",
        cgpa_percentage=85.0,
        category="General",
        annual_income=450000.0,
        state="Maharashtra",
        gender="Female",
        course="Undergraduate",
        field_of_study="STEM"
    )
    db.add(default_user)
    db.commit()

    # Seed relationship mappings for Jane Doe
    db.add(models.SavedScholarship(id=1, user_id=1, scholarship_id=1))
    db.add(models.SavedScholarship(id=2, user_id=1, scholarship_id=4))
    db.add(models.Application(id=1, user_id=1, scholarship_id=2, status="Applied", applied_date="2026-07-01"))
    db.commit()
    
    print("Database successfully seeded with 20 scholarships and a default user.")
    db.close()

if __name__ == "__main__":
    seed_db()
